spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # V(version)__description.sql
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

server:
  port: ${AGGREGATION_PORT}

app:
  keycloak:
    admin:
      clientId: ${AGGREGATION_KEYCLOAK_CLIENT_ID}
      clientSecret: ${AGGREGATION_KEYCLOAK_CLIENT_SECRET}
    realm: ${AGGREGATION_KEYCLOAK_REALM}
    serverUrl: ${AGGREGATION_KEYCLOAK_BASE_URL}
    defaultUserGroup: ${AGGREGATION_KEYCLOAK_DEFAULT_USER_GROUP}

# Logging
logging:
  level:
    org.springframework: ${AGGREGATION_LOGGER_LEVEL}
    com.tgdating: ${AGGREGATION_LOGGER_LEVEL}
